@startuml database

hide circle
skinparam linetype ortho

entity "Zone" as Zone {
    * _id : ObjectId
    --
    name : String
    description : String
}

entity "Lock" as Lock {
    * _id : ObjectId
    --
    name : String
    token : String
    zone: Zone
    online : Boolean
    lastSeen : Date
}

entity "AccessPass" as Pass {
    * _id : ObjectId
    --
    name : String
    uuid : String
    enabled : Boolean
    expiredAt : Date
}

entity "Event" as Event {
    * _id : ObjectId
    --
    type : String
    date : Date
}

Zone ||--o{ Lock : contains

Zone ||--o{ Pass : grants access

Lock ||--o{ Event : generates

Pass ||--o{ Event : used for

@enduml